# Generated by Django 3.1 on 2021-02-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_journey', '0006_auto_20200801_2319'),
        ('blog', '0003_post_content_cms'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoty',
            field=models.CharField(choices=[('OPN', 'Opinion'), ('STY', 'Story'), ('RVW', 'Review'), ('TRL', 'Tutorial'), ('EXL', 'Explanation')], default='STY', max_length=32),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='my_journey.TechStack'),
        ),
    ]
