# Generated by Django 3.0.7 on 2020-08-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='gpa',
            field=models.FloatField(null=True),
        ),
    ]
