# Generated by Django 3.0.7 on 2020-08-01 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_school_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_image', models.ImageField(upload_to='')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpa_images', to='education.School')),
            ],
        ),
    ]
