# Generated by Django 3.0.7 on 2020-08-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('cover_image', models.ImageField(upload_to='')),
                ('git_url', models.URLField()),
                ('youtube_url', models.URLField()),
            ],
        ),
    ]
