# Generated by Django 3.1 on 2020-08-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App',
            new_name='Aplication',
        ),
    ]
