# Generated by Django 3.1 on 2021-02-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_project', '0004_auto_20200821_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='project',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
